### ISSUE TITLE
Project Name

### ISSUE THREAD

**Issue by malex19889** [malex19889/Project2#7]

**Comment by celineross** [comment]
A Record for Your Records™

**Comment by cascutter** [comment]
Records are often kept in crates. So maybe CrateCatalog?

**Comment by xxmakveli22xx** [comment]
I like the Record for your Records

**Comment by cascutter** [comment]
Is there a way to condense that name?
Record Recorder?

**Comment by celineross** [comment]
THE Record Recorder?

**Comment by malex19889** [comment]
Record Traktor (tractor)

**Comment by cascutter** [comment]
Wax Tracker 
Vinyl Vault

**Comment by celineross** [comment]
Casandra's pick of **AudioFiler** is the winner
